# golangci-lint configuration for tmux-intray
# Focus on complexity metrics with conservative thresholds for existing codebase
version: "2"

linters:
  default: none
  enable:
    - gocyclo      # Cyclomatic complexity
    - gocognit     # Cognitive complexity
    - funlen       # Function length
    - nestif       # Nested if statements
    - staticcheck  # Static analysis
    - errcheck     # Error checking
  disable:
    - govet
    - unused
    - ineffassign
    - revive
  settings:
    gocyclo:
      min-complexity: 20
    gocognit:
      min-complexity: 30
    funlen:
      lines: 80
      statements: 50
    nestif:
      min-complexity: 5
  exclusions:
    presets: []
    paths:
      - .tmp
      - .gwt
      - .bv
      - .local
      - tmp
      - vendor
      - integration
      - integration/cmd
      - ".*_gen\\.go$"
      - "integration/.*\\.go$"
    rules:
      - path: (.+)_test\.go
        linters:
          - errcheck
          - funlen
      - path: (.+)_gen\.go
        linters:
          - gocyclo
          - gocognit
          - funlen