# golangci-lint configuration for tmux-intray
# Focus on complexity metrics with conservative thresholds for existing codebase
version: "2"

linters:
  default: none
  enable:
    - gocyclo      # Cyclomatic complexity
    - gocognit     # Cognitive complexity
    - funlen       # Function length
    - nestif       # Nested if statements
    - staticcheck  # Static analysis
    - errcheck     # Error checking
    - depguard     # Import/dependency guardrails
  disable:
    - govet
    - unused
    - ineffassign
    - revive
  settings:
    gocyclo:
      min-complexity: 20
    gocognit:
      min-complexity: 30
    funlen:
      lines: 80
      statements: 50
    nestif:
      min-complexity: 5
    depguard:
      rules:
        domain_no_infra:
          files:
            - internal/domain/**/*.go
          deny:
            - pkg: github.com/cristianoliveira/tmux-intray/internal/storage
              desc: domain must not depend on storage
            - pkg: github.com/cristianoliveira/tmux-intray/internal/storage/sqlite
              desc: domain must not depend on sqlite adapter
            - pkg: github.com/cristianoliveira/tmux-intray/internal/tmux
              desc: domain must not depend on tmux adapter

        cmd_no_sqlite_adapter:
          files:
            - cmd/**/*.go
          deny:
            - pkg: github.com/cristianoliveira/tmux-intray/internal/storage/sqlite
              desc: cmd should not import concrete sqlite adapter

        storage_no_new_tmux_edges:
          files:
            - internal/storage/**/*.go
            - '!**/*_test.go'
            - '!internal/storage/sqlite/tmux.go'
          deny:
            - pkg: github.com/cristianoliveira/tmux-intray/internal/tmux
              desc: storage should not depend on tmux (legacy file exempt during migration)
  exclusions:
    presets: []
    paths:
      - .tmp
      - .gwt
      - .bv
      - .local
      - tmp
      - vendor
      - integration
      - integration/cmd
      - ".*_gen\\.go$"
      - "integration/.*\\.go$"
    rules:
      - path: (.+)_test\.go
        linters:
          - errcheck
          - funlen
      - path: (.+)_gen\.go
        linters:
          - gocyclo
          - gocognit
          - funlen
