---
name: Bug Report
description: Report a bug or unexpected behavior in tmux-intray
title: "[BUG] "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the information below to help us reproduce and fix the issue.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of tmux-intray is affected?
      options:
        - CLI command
        - TUI interface
        - Storage/data
        - tmux integration
        - Configuration
        - Performance
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: tmux-intray version
      description: Run `tmux-intray version` to get the version
      placeholder: v1.0.0
    validations:
      required: true

  - type: input
    id: platform
    attributes:
      label: Platform details
      description: OS, shell, and tmux version
      placeholder: macOS 14, zsh, tmux 3.4
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Relevant configuration
      description: Include any relevant environment variables or config files
      placeholder: |
        TMUX_INTRAY_STORAGE_BACKEND=sqlite
        TMUX_INTRAY_DEBUG=1
        etc...
    validations:
      required: false

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this behavior?
      placeholder: |
        1. Run `tmux-intray add "test message"`
        2. Run `tmux-intray list`
        3. Observe the error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: The message should appear in the list
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: 'An error occurred: "failed to add tray item"'
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Debug Output
      description: Run with TMUX_INTRAY_DEBUG=1 and paste relevant output
      render: shell
      placeholder: Paste debug output here
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
      placeholder: Screenshots, related issues, etc.
    validations:
      required: false