name: SQLite opt-in feedback
description: Report bugs or feedback while using SQLite or dual backend rollout.
title: "[sqlite opt-in] "
labels:
  - sqlite
  - rollout
  - feedback
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping validate SQLite rollout in tmux-intray.
        Please include as much detail as possible to speed up triage.

  - type: dropdown
    id: backend_mode
    attributes:
      label: Backend mode
      description: Which backend mode were you using?
      options:
        - tsv
        - dual
        - sqlite
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: tmux-intray version
      placeholder: tmux-intray version
    validations:
      required: true

  - type: input
    id: platform
    attributes:
      label: Platform details
      description: OS, shell, and tmux version
      placeholder: macOS 14, zsh, tmux 3.4
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Relevant configuration
      description: Include TMUX_INTRAY_STORAGE_BACKEND and any TMUX_INTRAY_DUAL_* values.
      placeholder: |
        TMUX_INTRAY_STORAGE_BACKEND=dual
        TMUX_INTRAY_DUAL_READ_BACKEND=sqlite
        TMUX_INTRAY_DUAL_VERIFY_ONLY=0
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction steps
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Debug output
      description: Run with TMUX_INTRAY_DEBUG=1 and paste relevant output.
      render: shell
    validations:
      required: false
