#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
BIN_PATH="$PROJECT_ROOT/bin/tmux-intray"
MAN_DIR="$PROJECT_ROOT/man/man1"
DOCS_DIR="$PROJECT_ROOT/docs/cli"
VERSION="$("$BIN_PATH" version | awk '{print $NF}')"

# Create directories
mkdir -p "$MAN_DIR"
mkdir -p "$DOCS_DIR"

# Function to extract subcommand list with descriptions from main help
get_subcommands_with_descriptions() {
    "$BIN_PATH" --help | sed -n '/^COMMANDS:/,/^OPTIONS:/p' | grep -E '^    [a-z]' | sed 's/^    //' | while IFS= read -r line; do
        # Split line into signature and description (separated by two or more spaces)
        # Use sed to replace first occurrence of two or more spaces with '|'
        local processed
        processed="$(echo "$line" | sed -E 's/([[:space:]]{2,})/|/')"
        local signature="${processed%%|*}"
        local desc="${processed#*|}"
        # Trim leading/trailing spaces from description
        desc="$(echo "$desc" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
        # Extract command name (first word of signature)
        local cmd_name="${signature%% *}"
        echo "${cmd_name}|${signature}|${desc}"
    done
}

# Function to get help text for a subcommand if available
get_subcommand_help() {
    local cmd="$1"
    local help_output
    # Try --help, then -h
    help_output="$("$BIN_PATH" "$cmd" --help 2>/dev/null || "$BIN_PATH" "$cmd" -h 2>/dev/null)"
    # Filter out main help lines (those containing "tmux-intray v0.1.0" but not the command)
    if echo "$help_output" | grep -q "tmux-intray v0.1.0" && ! echo "$help_output" | grep -q "tmux-intray $cmd"; then
        # This is likely the main help, not subcommand help
        echo ""
        return
    fi
    # If output looks like help (contains "USAGE:" or "OPTIONS:" or starts with "tmux-intray"), return it
    if [[ "$help_output" =~ ^tmux-intray ]] || [[ "$help_output" =~ USAGE: ]] || [[ "$help_output" =~ OPTIONS: ]]; then
        echo "$help_output"
    else
        echo ""
    fi
}

# Generate markdown documentation
generate_markdown() {
    local md_file="$DOCS_DIR/CLI_REFERENCE.md"
    echo "Generating markdown documentation..."

    cat >"$md_file" <<EOF
# tmux-intray CLI Reference

Version: $VERSION

## Overview

tmux-intray is a quiet inbox for things that happen while you're not looking.

## Global Usage

\`\`\`
$("$BIN_PATH" --help)
\`\`\`

## Commands

EOF

    while IFS='|' read -r cmd_name signature desc; do
        echo "Processing $cmd_name..."
        local help_text
        help_text="$(get_subcommand_help "$cmd_name")"
        cat >>"$md_file" <<EOF
### $signature

$desc

EOF
        if [[ -n "$help_text" ]]; then
            # Clean up help text: remove duplicate main help lines
            # Keep only lines that are relevant to subcommand
            cat >>"$md_file" <<EOF
\`\`\`
$help_text
\`\`\`

EOF
        else
            cat >>"$md_file" <<EOF
*No detailed help available.*

EOF
        fi
    done < <(get_subcommands_with_descriptions)

    echo "Generated markdown: $md_file"
}

# Generate man page (custom roff)
generate_man_page() {
    local man_file="$MAN_DIR/tmux-intray.1"
    echo "Generating man page..."

    # Get current date in Month Year format
    local date_string
    date_string=$(date +"%B %Y")

    # Start writing man page
    cat >"$man_file" <<EOF
.\" Manpage for tmux-intray
.\" Generated automatically by scripts/generate-docs.sh
.\" DO NOT EDIT THIS FILE DIRECTLY
.TH TMUX\-INTRAY 1 "$date_string" "$VERSION" "tmux-intray Manual"
.SH NAME
tmux\-intray \- a quiet inbox for things that happen while you're not looking
.SH SYNOPSIS
.B tmux\-intray
[\fICOMMAND\fR] [\fIOPTIONS\fR]
.SH DESCRIPTION
tmux\-intray provides a persistent in\-tmux in\-tray where panes, windows, and scripts can drop messages and events without interrupting your flow. Instead of loud notifications or forced context switches, events accumulate calmly until you're ready to review them.
.PP
Each item keeps its origin, survives pane and window changes, and can be inspected, jumped to, or cleared at your own pace. It's designed for deferred attention: notice now if you want, act later when it makes sense.
.SH GLOBAL OPTIONS
.TP
\fB\-h, \-\-help\fR
Show help message
.SH COMMANDS
EOF

    # Add each command as a subsection
    while IFS='|' read -r cmd_name signature desc; do
        local help_text
        help_text="$(get_subcommand_help "$cmd_name")"

        cat >>"$man_file" <<EOF
.SS $signature
$desc
.PP
EOF
        if [[ -n "$help_text" ]]; then
            # Format help text as preformatted block
            cat >>"$man_file" <<EOF
.nf
$help_text
.fi
.PP
EOF
        fi
    done < <(get_subcommands_with_descriptions)

    # Add footer sections
    cat >>"$man_file" <<EOF
.SH FILES
.TP
\fI~/.local/state/tmux\-intray/\fR
Notification storage directory (XDG Base Directory Specification)
.TP
\fI~/.config/tmux\-intray/config.sh\fR
Configuration file
.TP
\fI~/.config/tmux\-intray/hooks/\fR
Hook scripts directory
.SH SEE ALSO
.IR tmux (1)
.SH AUTHOR
Cristian Oliveira and contributors
.SH COPYRIGHT
Copyright \(co 2026 Cristian Oliveira
.br
MIT License
EOF

    echo "Generated man page: $man_file"
}

# Main
generate_markdown
generate_man_page

echo "Documentation generation complete."
