// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

type Notification struct {
	ID            int64
	Timestamp     string
	State         string
	Session       string
	Window        string
	Pane          string
	Message       string
	PaneCreated   string
	Level         string
	ReadTimestamp string
	UpdatedAt     string
}

type TelemetryEvent struct {
	ID              int64
	Timestamp       string
	FeatureName     string
	FeatureCategory string
	ContextData     string
}
